const menu = [
    {dish: "Консоме с трюфельными крошками", calories: 150, weight: 250, price: 990, type: "Основное"},
    {dish: "Французский луковый суп 'Гратен'", calories: 200, weight: 300, price: 1275, type: "Суп"},
    {dish: "Классический никозиенский салат", calories: 180, weight: 200, price: 1085, type: "Салат"},
    {dish: "Креветки в чесночном соусе", calories: 250, weight: 220, price: 1585, type: "Основное"},
    {dish: "Печеный картофель 'Бульба дюшес'", calories: 220, weight: 180, price: 1485, type: "Основное"},
    {dish: "Тартар из лосося с каперсами", calories: 280, weight: 200, price: 1835, type: "Основное"},
    {dish: "Гренки с картошкой и шампиньонами", calories: 230, weight: 180, price: 1350, type: "Основное"},
    {dish: "Буффало-моцарелла с помидорами и базиликом", calories: 280, weight: 250, price: 1725, type: "Основное"},
    {dish: "Жюльен из индейки с грибами", calories: 220, weight: 230, price: 1435, type: "Основное"},
    {dish: "Конфитюр из фуа-гра с гренками", calories: 320, weight: 200, price: 1980, type: "Основное"},
    {dish: "Печеные креветки в чили-соусе", calories: 260, weight: 240, price: 1650, type: "Основное"},
    {dish: "Тарт с лимонным курдом", calories: 180, weight: 180, price: 1270, type: "Основное"},
    {dish: "Красный окунь в белом вине", calories: 280, weight: 220, price: 1795, type: "Основное"},
    {dish: "Фондю с ароматными травами", calories: 320, weight: 300, price: 2080, type: "Основное"},
    {dish: "Сельдь в масле с луком", calories: 180, weight: 150, price: 995, type: "Основное"},
    {dish: "Рататуй с томатным соусом", calories: 200, weight: 200, price: 1290, type: "Основное"},
    {dish: "Гренки с тунцом и авокадо", calories: 250, weight: 230, price: 1650, type: "Основное"},
    {dish: "Шарлотка с ягодами", calories: 220, weight: 180, price: 1345, type: "Основное"},
    {dish: "Фаршированные грибы с сыром", calories: 180, weight: 160, price: 1160, type: "Основное"},
    {dish: "Гречка по-французски", calories: 220, weight: 200, price: 1385, type: "Основное"},
    {dish: "Суп 'Минестроне' с белыми бобами", calories: 220, weight: 300, price: 1450, type: "Суп"},
    {dish: "Картофельный пюре с трюфельным маслом", calories: 200, weight: 200, price: 1325, type: "Основное"},
    {dish: "Филе куриного молодого гуся", calories: 300, weight: 280, price: 1985, type: "Основное"},
    {dish: "Карпаччо из телятины с рукколой", calories: 240, weight: 220, price: 1675, type: "Основное"},
    {dish: "Омлет с травами и пармезаном", calories: 180, weight: 200, price: 1150, type: "Основное"},
    {dish: "Паста 'Карбонара' с беконом", calories: 320, weight: 250, price: 1950, type: "Основное"},
    {dish: "Сливочный рис с малиновым кули", calories: 220, weight: 180, price: 1395, type: "Основное"},
    {dish: "Террин из гусиных печенок", calories: 280, weight: 300, price: 2090, type: "Основное"},
    {dish: "Суп 'Бульон' с клецками", calories: 180, weight: 200, price: 1155, type: "Суп"},
    {dish: "Говядина 'Сюрф и турф' с соусом борделе", calories: 350, weight: 280, price: 2150, type: "Основное"},
    {dish: "Паста 'Путтанеска' с морепродуктами", calories: 300, weight: 250, price: 1890, type: "Основное"},
    {dish: "Красная рыба с карри и лимонной травой", calories: 280, weight: 220, price: 1675, type: "Основное"},
    {dish: "Куриный пай с лесными грибами", calories: 320, weight: 300, price: 1985, type: "Пирог"},
    {dish: "Острицы 'Гильардо' с лимоном", calories: 150, weight: 200, price: 980, type: "Основное"},
    {dish: "Спагетти с тунцовым соусом", calories: 260, weight: 230, price: 1595, type: "Основное"},
    {dish: "Салат 'Нисуаз' с тунцом", calories: 320, weight: 250, price: 1980, type: "Салат"},
    {dish: "Фриттата с картошкой и луком", calories: 220, weight: 180, price: 1345, type: "Основное"},
    {dish: "Семга с авокадо и соевым соусом", calories: 250, weight: 220, price: 1590, type: "Основное"},
    {dish: "Горчичные креветки с медовым соусом", calories: 280, weight: 240, price: 1795, type: "Основное"},
    {dish: "Ризотто с трюфелями", calories: 300, weight: 220, price: 1485, type: "Основное"},
    {dish: "Конфитюр из лимонов с мятой", calories: 120, weight: 150, price: 715, type: "Основное"},
    {dish: "Говядина 'Бургуньон' с картошкой", calories: 250, weight: 280, price: 1685, type: "Основное"},
    {dish: "Сливочный суп с лососем", calories: 220, weight: 200, price: 1375, type: "Суп"},
    {dish: "Салат с ростбифом и горчичным соусом", calories: 280, weight: 300, price: 2075, type: "Салат"},
    {dish: "Фруктовый салат с мятным сиропом", calories: 150, weight: 180, price: 1035, type: "Салат"},
    {dish: "Креп 'Сюзетт' с апельсиновым соусом", calories: 200, weight: 250, price: 1550, type: "Основное"},
    {dish: "Лосось с грейпфрутовым соусом", calories: 280, weight: 250, price: 1790, type: "Основное"},
    {dish: "Сырные палочки с соусом песто", calories: 180, weight: 220, price: 1150, type: "Закуска"},
    {dish: "Брускетта с томатами и базиликом", calories: 150, weight: 180, price: 980, type: "Закуска"},
    {dish: "Карпаччо из лосося с кремом из хрена", calories: 240, weight: 200, price: 1650, type: "Закуска"},
    {dish: "Равиоли с креветками и шпинатом", calories: 280, weight: 250, price: 1820, type: "Основное"},
    {dish: "Телятина в соусе 'Мадера'", calories: 300, weight: 240, price: 2150, type: "Основное"},
    {dish: "Куриные крылья с BBQ соусом", calories: 320, weight: 300, price: 1480, type: "Основное"},
    {dish: "Паста с сыром 'Горгонзола'", calories: 310, weight: 270, price: 1620, type: "Основное"},
    {dish: "Салат с рукколой и сыром 'Пармезан'", calories: 200, weight: 220, price: 1380, type: "Салат"},
    {dish: "Тирамису с малиновым соусом", calories: 280, weight: 200, price: 1450, type: "Десерт"},
    {dish: "Чизкейк с черничным джемом", calories: 320, weight: 210, price: 1590, type: "Десерт"},
    {dish: "Филе миньон с трюфельным соусом", calories: 350, weight: 280, price: 2350, type: "Основное"},
    {dish: "Запеченные баклажаны с пармезаном", calories: 200, weight: 230, price: 1230, type: "Основное"},
    {dish: "Крем-брюле с клубничным компоте", calories: 190, weight: 180, price: 1330, type: "Десерт"},
    {dish: "Горячий шоколад с взбитыми сливками", calories: 220, weight: 150, price: 990, type: "Десерт"},
    {dish: "Куриные наггетсы с соусом сладкий чили", calories: 250, weight: 200, price: 1200, type: "Закуска"},
    {dish: "Тосты с авокадо и лососем", calories: 270, weight: 180, price: 1450, type: "Закуска"},
    {dish: "Гаспачо с хрустящими крутонами", calories: 120, weight: 250, price: 950, type: "Суп"},
    {dish: "Бургер с говяжьей котлетой и соусом айоли", calories: 550, weight: 320, price: 1750, type: "Основное"},
    {dish: "Кесадилья с курицей и сыром", calories: 400, weight: 280, price: 1580, type: "Основное"},
    {dish: "Тортилья с овощами-гриль и сыром", calories: 350, weight: 240, price: 1495, type: "Основное"},
    {dish: "Пицца с моцареллой и помидорами", calories: 600, weight: 400, price: 1680, type: "Основное"},
    {dish: "Мясной рулет с сыром и шпинатом", calories: 450, weight: 320, price: 1885, type: "Основное"},
    {dish: "Шоколадный фондан с ванильным мороженым", calories: 350, weight: 180, price: 1650, type: "Десерт"},
    {dish: "Панна-котта с ягодным соусом", calories: 240, weight: 150, price: 1300, type: "Десерт"},
    {dish: "Сырный суп с гренками", calories: 300, weight: 270, price: 1450, type: "Суп"},
    {dish: "Салат с креветками и соусом 'Цезарь'", calories: 260, weight: 220, price: 1650, type: "Салат"},
    {dish: "Запеченные мидии с чесноком и сыром", calories: 280, weight: 200, price: 1850, type: "Закуска"},
    {dish: "Карамелизированные яблоки с корицей", calories: 200, weight: 180, price: 1100, type: "Десерт"},
    {dish: "Шашлык из баранины с овощами на гриле", calories: 520, weight: 350, price: 2150, type: "Основное"},
    {dish: "Картофель фри с трюфельным маслом", calories: 350, weight: 250, price: 1250, type: "Закуска"},
    {dish: "Сорбет из манго с мятой", calories: 150, weight: 120, price: 950, type: "Десерт"},
    {dish: "Суп 'Том Ям' с креветками", calories: 320, weight: 300, price: 1850, type: "Суп"},
    {dish: "Паста с чернилами кальмара и морепродуктами", calories: 400, weight: 270, price: 2050, type: "Основное"},
    {dish: "Филе утки в соусе из черной смородины", calories: 480, weight: 300, price: 2250, type: "Основное"}
];
